routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// use App\Http\Controllers\PublicController;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\SearchController;

Route::get('/', function () {
    return view('welcome');
});
// Route::get('admin', 'AdminHomeController@index')->name('admin.dashboard');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('index', 'PublicController');
Route::resource('admin', 'AdminHomeController');
Route::put('products/{id}/feature', 'ProductsController@feature')->name('prod.update');
Route::get('product/{id}', 'HomeController@product')->name('product');
Route::post('search', 'HomeController@search')->name('search');
Route::post('home', 'HomeController@searchHome')->name('home');
Route::get('checkout', 'ProductsController@checkout')->name('checkout');
Route::get('register', 'ProductsController@register')->name('register');


Route::get('/shoppers', 'HomeController@index');
Route::get('/ind', 'PublicController@index');
Route::get('/shop', 'HomeController@shop');
Route::get('/show/{id}', 'HomeController@show')->name('show');
Route::get('/cart1', 'HomeController@cart1');
Route::get('add-to-cart/{id}', 'HomeController@addToCart')->name('add');
Route::patch('update-cart', 'HomeController@update');
Route::delete('remove', 'HomeController@remove');


Route::get('/search', 'SearchController@search');
Route::get('/index', 'SearchController@index');


// Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cats = Category::all();
        $related = Product::all();
        // $product = Product::where('discount_price', '>', 30)->get();
        $product = Product::first();
        // dd($product);
        $products = Product::with('category')->get();

        // dd('got here');
        return view('shopIndex', compact('cats', 'related', 'products', 'product'));
    }

    public function product($id)
    {
        $item = Product::findOrFail($id);
        $products = Product::where('category_id', $item->id)->get();
        $related = Product::all();

        return response()->json($products);
        // return view('product', compact('related', 'products'));
    }


    public function shop()
    {
        $cats = Category::all();
        $related = Product::all();
        $product = Product::where('discount_price', '>', 300)->get();
        $categories = Category::withCount('Products')->get();
        // dd($categories);
        $products = Product::with('category')->paginate(5);

        // dd('got here');
        return view('shop', compact('cats', 'related', 'products', 'product', 'categories'));
    }
    public function show($id)
    {
        $product = Product::findOrfail($id);
        // dd($product);
        $related = Product::all();
        $cats = Category::withCount('Products')->get();


        // return response()->json([
        //     'product' => $product,
        //     'related' => $related
        // ]);

        return view('shopSingle', compact('product', 'related', 'cats'));
    }



    public function search(Request $request)
    {
        $item = $request->input('search');

        $products = Product::where('title', 'lIKE', '%' . $item . '%')->get();

        return response()->json($products);
    }


    public function cart1()
    {
        return view('cart1');
    }


    public function addToCart($id)
    {
        $product = Product::find($id);

        if (!$product) {

            abort(404);
        }

        $cart = session()->get('cart');

        // if cart is empty then this the first product
        if (!$cart) {

            $cart = [
                $id => [
                    "name" => $product->title,
                    "quantity" => 1,
                    "price" => $product->original_price,
                    "photo" => $product->image
                ]
            ];

            session()->put('cart', $cart);

            return redirect()->back()->with('success', 'Product added to cart successfully!');
        }

        // if cart not empty then check if this product exist then increment quantity
        if (isset($cart[$id])) {

            $cart[$id]['quantity']++;

            session()->put('cart', $cart);

            return redirect()->back()->with('success', 'Product added to cart successfully!');
        }

        // if item not exist in cart then add to cart with quantity = 1

        $cart[$id] = [
            "name" => $product->title,
            "quantity" => 1,
            "price" => $product->original_price,
            "photo" => $product->image
        ];

        session()->put('cart', $cart);

        return redirect()->back()->with('success', 'Product added to cart successfully!');
    }


    public function update(Request $request)
    {
        if ($request->id && $request->quantity) {
            $cart = session()->get('cart');

            $cart[$request->id]["quantity"] = $request->quantity;

            session()->put('cart', $cart);

            session()->flash('success', 'Cart updated successfully');
        }
    }

    public function remove(Request $request)
    {
        if ($request->id) {

            $cart = session()->get('cart');

            if (isset($cart[$request->id])) {

                unset($cart[$request->id]);

                session()->put('cart', $cart);
            }

            session()->flash('success', 'Product removed successfully');
        }
    }
}

resources/views/cart.blade.php
@extends('layouts.app')


@section('content')

<table id="cart" class="table table-hover table-condensed" style="margin-left:50px;">
    <thead>
        <tr>
            <th style="width:50%">Product</th>
            <th style="width:10%">Price</th>
            <th style="width:8%">Quantity</th>
            <th style="width:22%" class="text-center">Subtotal</th>
            <th style="width:10%"></th>
        </tr>
    </thead>
    <tbody>

        <?php $total = 0 ?>

        @if(session('cart'))
        @foreach(session('cart') as $id => $details)

        <?php $total += $details['price'] * $details['quantity'] ?>

        <tr>
            <td data-th="Product">
                <div class="row">
                    <div class="col-sm-3 hidden-xs"><img src="{{asset('storage/'. $details['photo'] )}}" width="100"
                            height="100" class="img-responsive" /></div>
                    <div class="col-sm-9">
                        <h4 class="nomargin">{{ $details['name'] }}</h4>
                    </div>
                </div>
            </td>
            <td data-th="Price">${{ $details['price'] }}</td>
            <td data-th="Quantity">
                <input type="number" value="{{ $details['quantity'] }}" class="form-control quantity" />
            </td>
            <td data-th="Subtotal" class="text-center">${{ $details['price'] * $details['quantity'] }}</td>
            <td class="actions" data-th="">
                <button class="btn btn-info btn-sm update-cart" id="{{ $id }}"><i class="fa fa-refresh"></i></button>
                <button class="btn btn-danger btn-sm remove-from-cart" id="{{ $id }}"><i
                        class="fa fa-trash-o"></i></button>
            </td>
        </tr>
        @endforeach
        @endif

    </tbody>
    <tfoot>
        <tr class="visible-xs">
            <td class="text-center"><strong>Total {{ $total }}</strong></td>
        </tr>
        <tr>
            <td><a href="{{ url('/') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue
                    Shopping</a></td>
            <td colspan="2" class="hidden-xs"></td>
            <td class="hidden-xs text-center"><strong>Total ${{ $total }}</strong></td>
        </tr>
    </tfoot>
</table>

@endsection

@section('scripts')


<script type="text/javascript">
    $(".update-cart").click(function (e) {
        e.preventDefault();

        var ele = $(this);

        $.ajax({
            url: '{{ url('update-cart') }}',
            method: "patch",
            data: {_token: '{{ csrf_token() }}', id: ele.attr("id"), quantity: ele.parents("tr").find(".quantity").val()},
            success: function (response) {
            window.location.reload();
            }
        });
    });

    $(".remove-from-cart").click(function (e) {
            e.preventDefault();

                var ele = $(this);

            if(confirm("U're removing this item ORACLE?")) {
                 $.ajax({
                        url: '{{ url('remove-from-cart') }}',
                        method: "DELETE",
                        data: {_token: '{{ csrf_token() }}', id: ele.attr("id")},
                        success: function (response) {
                            window.location.reload();
                        }
                });
            }
     });


</script>
@endsection

resources/views/cart1.blade.php
@extends('layouts.shoppers')

@section('content')
<div class="bg-light py-3" id="cart">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong
                    class="text-black">Cart</strong></div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container" id="products">
        <div class="row mb-5">
            <form class="col-md-12" method="">
                <div class="site-blocks-table">
                    <table class="table table-bordered" id="cart">
                        <thead>
                            <tr>
                                <th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-total">Sub Total</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $total = 0?>

                            @if(session('cart'))

                            @foreach (session('cart') as $id => $product)

                            <?php $total += $product['price'] * $product['quantity'] ?>

                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{asset('storage/' . $product['photo'])}}" alt="Image" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{$product['name']}}</h2>
                                </td>
                                <td>${{$product['price']}}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <button class="btn btn-outline-primary js-btn-minus"
                                                type="button">&minus;</button>
                                        </div>
                                        <input type="text" class="form-control text-center quantity"
                                            value="{{ $product['quantity'] }}" placeholder=""
                                            aria-label="Example text with button addon"
                                            aria-describedby="button-addon1">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-primary js-btn-plus"
                                                type="button">&plus;</button>
                                        </div>
                                    </div>

                                </td>
                                <td>${{ $product['price'] * $product['quantity'] }}</td>
                                <td class="actions" data-th="">

                                    <button class="btn btn-danger btn-sm remove-from-cart"
                                        data-id="{{ $id }}">Remove</button>
                                </td>
                            </tr>
                            @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-6 mb-3 mb-md-0">
                        <button data-id="{{session('id')}}" class="btn btn-primary btn-sm btn-block update-cart">Update
                            Cart</button>
                    </div>
                    <div class="col-md-6">
                        <a href="{{url('shop')}}">
                            <button class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</button>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label class="text-black h4" for="coupon">Coupon</label>
                        <p>Enter your coupon code if you have one.</p>
                    </div>
                    <div class="col-md-8 mb-3 mb-md-0">
                        <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                    </div>
                    <div class="col-md-4">
                        <button class="btn btn-primary btn-sm">Apply Coupon</button>
                    </div>
                </div>
            </div>
            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>
                        {{-- <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">Subtotal</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">${{ $product['price'] * $product['quantity'] }}</strong>
                    </div>
                </div> --}}
                <div class="row mb-5">
                    <div class="col-md-6">
                        <span class="text-black">Total</span>
                    </div>
                    <div class="col-md-6 text-right">
                        <strong class="text-black">${{$total}}</strong>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <button class="btn btn-primary btn-sm py-3 btn-block"
                            onclick="window.location='register'">Proceed To Checkout</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection
@section('scripts')


<script type="text/javascript">
    $(".update-cart").click(function (e) {
           e.preventDefault();

           var ele = $(this);

            $.ajax({
               url: '{{ url('update-cart') }}',
               method: "patch",
               data: {_token: '{{ csrf_token() }}', id: ele.attr("data-id"), quantity: ele.parents("tr").find(".quantity").val()},
               success: function (response) {
                   window.location.reload();
               }
            });
        });

        $(".remove-from-cart").click(function (e) {
            e.preventDefault();

            var ele = $(this);

            if(confirm("Are you sure ORACLE?")) {
                $.ajax({
                    url: '{{ url('remove') }}',
                    method: "DELETE",
                    data: {_token: '{{ csrf_token() }}', id: ele.attr("data-id")},
                    success: function (response) {
                        window.location.reload();
                    }
                });
            }
        });

</script>

@endsection

resources/views/checkout.blade.php
@extends('layouts.shoppers')

@section('content')
<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-12">
                <h2 class="h3 mb-3 text-black">Your Order</h2>
                <div class="p-3 p-lg-5 border">
                    <table class="table site-block-order-table mb-5">
                        <thead>
                            <th>Product</th>
                            <th>Total</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Top Up T-Shirt <strong class="mx-2">x</strong> 1</td>
                                <td>$250.00</td>
                            </tr>
                            <tr>
                                <td>Polo Shirt <strong class="mx-2">x</strong> 1</td>
                                <td>$100.00</td>
                            </tr>
                            <tr>
                                <td class="text-black font-weight-bold"><strong>Cart Subtotal</strong></td>
                                <td class="text-black">$350.00</td>
                            </tr>
                            <tr>
                                <td class="text-black font-weight-bold"><strong>Order Total</strong></td>
                                <td class="text-black font-weight-bold"><strong>$350.00</strong></td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="border p-3 mb-3">
                        <h3 class="h6 mb-0"><a class="d-block" data-toggle="collapse" href="#collapsebank" role="button"
                                aria-expanded="false" aria-controls="collapsebank">Direct Bank
                                Transfer</a></h3>

                        <div class="collapse" id="collapsebank">
                            <div class="py-2">
                                <p class="mb-0">Make your payment directly into our bank account. Please use
                                    your Order ID as the payment reference. Your order won’t be shipped until
                                    the funds have cleared in our account.</p>
                            </div>
                        </div>
                    </div>

                    <div class="border p-3 mb-3">
                        <h3 class="h6 mb-0"><a class="d-block" data-toggle="collapse" href="#collapsecheque"
                                role="button" aria-expanded="false" aria-controls="collapsecheque">Cheque
                                Payment</a></h3>

                        <div class="collapse" id="collapsecheque">
                            <div class="py-2">
                                <p class="mb-0">Make your payment directly into our bank account. Please use
                                    your Order ID as the payment reference. Your order won’t be shipped until
                                    the funds have cleared in our account.</p>
                            </div>
                        </div>
                    </div>

                    <div class="border p-3 mb-5">
                        <h3 class="h6 mb-0"><a class="d-block" data-toggle="collapse" href="#collapsepaypal"
                                role="button" aria-expanded="false" aria-controls="collapsepaypal">Paypal</a>
                        </h3>

                        <div class="collapse" id="collapsepaypal">
                            <div class="py-2">
                                <p class="mb-0">Make your payment directly into our bank account. Please use
                                    your Order ID as the payment reference. Your order won’t be shipped until
                                    the funds have cleared in our account.</p>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary btn-sm py-3 btn-block"
                            onclick="window.location='thankyou.html'">Place
                            Order</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/shop.blade.php
@extends('layouts.shoppers')

@section('content')

<div class="site-wrap">
    {{-- @include('shoppers.header') --}}
    <div class="bg-light py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0"><a href="{{url('shoppers')}}">Home</a> <span class="mx-2 mb-0">/</span>
                    <strong class="text-black">Shop</strong></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="site-section">

            <div class="row mb-5">
                <div class="col-md-9 order-2">

                    <div class="row">
                        <div class="col-md-12 mb-5">
                            <div class="float-md-left mb-4">
                                <h2 class="text-black h5">Shop All</h2>
                            </div>
                            <div class="d-flex">
                                <div class="dropdown mr-1 ml-md-auto">
                                    <button type="button" class="btn btn-secondary btn-sm dropdown-toggle"
                                        id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        Latest
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                                        @foreach ($categories as $cat)

                                        <a class="dropdown-item cat" href="">{{$cat->name}}
                                            <input type="hidden" value="{{$cat->id}}" />

                                        </a>
                                        @endforeach

                                    </div>
                                </div>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-secondary btn-sm dropdown-toggle"
                                        id="dropdownMenuReference" data-toggle="dropdown">Reference</button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                                        <a class="dropdown-item" href="#">Relevance</a>
                                        <a class="dropdown-item" href="#">Name, A to Z</a>
                                        <a class="dropdown-item" href="#">Name, Z to A</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Price, low to high</a>
                                        <a class="dropdown-item" href="#">Price, high to low</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mb-5" id="products">

                        @foreach ($products as $product)
                        <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                            <div class="block-4 text-center border">
                                <figure class="block-4-image">
                                    <a href="{{ route('show', $product->id) }}"><img
                                            src="{{asset('storage/'. $product->image)}}" alt="Image placeholder"
                                            class="img-fluid" style="height:200px;">
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3>{{$product->title}}</h3>
                                    <p class="mb-0">Finding perfect products</p>
                                    <p class="text-primary font-weight-bold">${{$product->original_price}}</p></a>
                                    <a href="{{url('add-to-cart', $product->id)}}">
                                        <button id="" class="btn btn-primary btn-sm centa add-to-cart">Add to cart
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        @endforeach

                    </div>
                    <div class="row" data-aos="fade-up">
                        <div class="col-md-12 text-center">
                            <div class="site-block-27">
                                <ul style="margin-left:40%">
                                    {{$products->links()}}

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 order-1 mb-5 mb-md-0">
                    <div class="border p-4 rounded mb-4">
                        <h3 class="mb-3 h6 text-uppercase text-black d-block">Categories</h3>
                        <ul class="list-unstyled mb-0">
                            @foreach ($categories as $count)
                            <li class="mb-1">
                                {{-- <a href="{{url('product', $count->id)}}" class="d-flex cat"> --}}

                                <a href="" class="d-flex cat">
                                    <input type="hidden" value="{{$count->id}}" />
                                    <span>{{$count->name}}</span>
                                    <span class="text-black ml-auto">{{$count->products_count}}</span>
                                </a>
                            </li>
                            @endforeach
                        </ul>

                    </div>

                    <div class="border p-4 rounded mb-4">
                        <div class="mb-4">
                            <h3 class="mb-3 h6 text-uppercase text-black d-block">Filter by Price</h3>
                            <div id="slider-range" class="border-primary"></div>
                            <input type="text" name="text" id="amount" class="form-control border-0 pl-0 bg-white"
                                disabled="" />
                        </div>


                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="site-section site-blocks-2">
                        <div class="row justify-content-center text-center mb-5">
                            <div class="col-md-7 site-section-heading pt-4">
                                <h2>Categories</h2>
                            </div>
                        </div>
                        <div class="row">
                            @foreach ($cats as $cat)
                            <div class="col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
                                <a class="block-2-item" href="#">
                                    <figure class="image">
                                        <img src="{{asset('storage/'. $cat->image)}}" alt="" class="img-fluid"
                                            style="height:330px">
                                    </figure>
                                    <div class="text">
                                        <span class="text-uppercase">Collections</span>
                                        <h3>{{$cat->name}}</h3>
                                    </div>
                                </a>
                            </div>
                            @endforeach

                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
@yield('scripts')
<script>
    // script for latest


// latest link script end

// category link script begin
    $(document).ready(function(){
        $('.cat').on("click",function(e){
            e.preventDefault();
            const id = $(this).find('input').val();
            let url = "{{ route('product', '%id%')}}" ;
            url = url.replace('%id%', id)

            $.ajax({
                url: url,
                method: "GET",
                data:{
                    id: id,
                },
                success: function (response) {
                    let output = ''
                    // console.log(response)
                    response.forEach(item => {
                    let url = "{{ route('show', '%id%')}}" ;
                    url = url.replace('%id%', item.id)
                    let asset = "{{ asset('storage/%image%')}}"
                    asset = asset.replace('%image%', item.image)

                    let url1 = "{{ route('add', '%id%')}}"
                    url1 = url1.replace('%id%', item.id)
                    // console.log(url)
                    let container = htmlContainer(url, asset, item, url1)

                    output += container;
                    });
                    $('#products').html(output);
                    console.log('Response ',response)
                }

            })
        })
    })

    // category link script ends
</script>
@endsection