routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// use App\Http\Controllers\PublicController;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\SearchController;

Route::get('/', function () {
    return view('welcome');
});
// Route::get('admin', 'AdminHomeController@index')->name('admin.dashboard');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('index', 'PublicController');
Route::resource('admin', 'AdminHomeController');
Route::put('products/{id}/feature', 'ProductsController@feature')->name('prod.update');
Route::get('product/{id}', 'HomeController@product')->name('product');
Route::post('search', 'HomeController@search')->name('search');
Route::post('home', 'HomeController@searchHome')->name('home');
Route::get('checkout', 'ProductsController@checkout')->name('checkout');
Route::get('register', 'ProductsController@register')->name('register');


Route::get('/shoppers', 'HomeController@index');
Route::get('/ind', 'PublicController@index');
Route::get('/shop', 'HomeController@shop');
Route::get('/show/{id}', 'HomeController@show')->name('show');
Route::get('/cart1', 'HomeController@cart1');
Route::get('add-to-cart/{id}', 'HomeController@addToCart')->name('add');
Route::patch('update-cart', 'HomeController@update');
Route::delete('remove', 'HomeController@remove');


Route::get('/search', 'SearchController@search');
Route::get('/index', 'SearchController@index');


// Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/includes/customtemplate.blade.php
<div class="custom-template">
    <div class="title">Settings</div>
    <div class="custom-content">
        <div class="switcher">
            <div class="switch-block">
                <h4>Logo Header</h4>
                <div class="btnSwitch">
                    <button type="button" class="changeLogoHeaderColor" data-color="dark"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="blue"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="purple"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="light-blue"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="green"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="orange"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="red"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="white"></button>
                    <br />
                    <button type="button" class="selected changeLogoHeaderColor" data-color="dark2"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="blue2"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="purple2"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="light-blue2"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="green2"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="orange2"></button>
                    <button type="button" class="changeLogoHeaderColor" data-color="red2"></button>
                </div>
            </div>
            <div class="switch-block">
                <h4>Navbar Header</h4>
                <div class="btnSwitch">
                    <button type="button" class="selected changeTopBarColor" data-color="dark"></button>
                    <button type="button" class="changeTopBarColor" data-color="blue"></button>
                    <button type="button" class="changeTopBarColor" data-color="purple"></button>
                    <button type="button" class="changeTopBarColor" data-color="light-blue"></button>
                    <button type="button" class="changeTopBarColor" data-color="green"></button>
                    <button type="button" class="changeTopBarColor" data-color="orange"></button>
                    <button type="button" class="changeTopBarColor" data-color="red"></button>
                    <button type="button" class="changeTopBarColor" data-color="white"></button>
                    <br />
                    <button type="button" class="changeTopBarColor" data-color="dark2"></button>
                    <button type="button" class="changeTopBarColor" data-color="blue2"></button>
                    <button type="button" class="changeTopBarColor" data-color="purple2"></button>
                    <button type="button" class="changeTopBarColor" data-color="light-blue2"></button>
                    <button type="button" class="changeTopBarColor" data-color="green2"></button>
                    <button type="button" class="changeTopBarColor" data-color="orange2"></button>
                    <button type="button" class="changeTopBarColor" data-color="red2"></button>
                </div>
            </div>
            <div class="switch-block">
                <h4>Sidebar</h4>
                <div class="btnSwitch">
                    <button type="button" class="changeSideBarColor" data-color="white"></button>
                    <button type="button" class="changeSideBarColor" data-color="dark"></button>
                    <button type="button" class="selected changeSideBarColor" data-color="dark2"></button>
                </div>
            </div>
            <div class="switch-block">
                <h4>Background</h4>
                <div class="btnSwitch">
                    <button type="button" class="changeBackgroundColor" data-color="bg2"></button>
                    <button type="button" class="changeBackgroundColor selected" data-color="bg1"></button>
                    <button type="button" class="changeBackgroundColor" data-color="bg3"></button>
                    <button type="button" class="selected changeBackgroundColor" data-color="dark"></button>
                </div>
            </div>
        </div>
    </div>
    <div class="custom-toggle">
        <i class="flaticon-settings"></i>
    </div>
</div>

resources/views/includes/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="https://www.themekita.com">
                        ThemeKita
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Help
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Licenses
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright ml-auto">
            2018, made with <i class="fa fa-heart heart text-danger"></i> by <a
                href="https://www.themekita.com">ThemeKita</a>
        </div>
    </div>
</footer>

resources/views/includes/footer1.blade.php
<footer class="site-footer border-top">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="footer-heading mb-4">Navigations</h3>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <ul class="list-unstyled">
                            <li><a href="#">Sell online</a></li>
                            {{-- <li><a href="#">Features</a></li> --}}
                            <li><a href="{{url('cart1')}}">Shopping cart</a></li>
                            {{-- <li><a href="#">Store builder</a></li> --}}
                        </ul>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <ul class="list-unstyled">
                            {{-- <li><a href="#">Mobile commerce</a></li> --}}
                            <li><a href="#">Dropshipping</a></li>
                            <li><a href="#">Website development</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-lg-4">
                        <ul class="list-unstyled">
                            <li><a href="#">Point of sale</a></li>
                            {{-- <li><a href="#">Hardware</a></li>
                        <li><a href="#">Software</a></li> --}}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
                <h3 class="footer-heading mb-4">Promo</h3>
                <a href="{{url('shop')}}" class="block-6">
                    <img src="{{asset('assetShop/images/hero_1.jpg')}}" alt="Image placeholder"
                        class="img-fluid rounded mb-4">
                    <h3 class="font-weight-light  mb-0">Finding Your Perfect outfit</h3>
                    <p>Promo: From December 15 &mdash; 25, 2019</p>
                </a>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="block-5 mb-5">
                    <h3 class="footer-heading mb-4">Contact Info</h3>
                    <ul class="list-unstyled">
                        <li class="address">SUITE D6, Goshen Plaza, Enugu, NIGERIA</li>
                        <li class="phone"><a href="tel://23923929210">+2348032740517</a></li>
                        <li class="email">iykee@yahoo.com</li>
                    </ul>
                </div>

                <div class="block-7">
                    <form action="#" method="post">
                        <label for="email_subscribe" class="footer-heading">Subscribe</label>
                        <div class="form-group">
                            <input type="text" class="form-control py-4" id="email_subscribe" placeholder="Email">
                            <input type="submit" class="btn btn-sm btn-primary" value="Send">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
            <div class="col-md-12">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script data-cfasync="false"
                        src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>
                        document.write(new Date().getFullYear());
                    </script> All rights reserved | This design is made with <i class="icon-heart"
                        aria-hidden="true"></i>
                    by <a href="https://smartArchive.com" target="_blank" class="text-primary">Afrivelle Technology</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>

        </div>
    </div>
</footer>

resources/views/includes/footerlinks.blade.php
<script src="{{asset('assets/js/core/jquery.3.2.1.min.js')}}"></script>
<script src="{{asset('assets/js/core/popper.min.js')}}"></script>
<script src="{{asset('assets/js/core/bootstrap.min.js')}}"></script>

<!-- jQuery UI -->
<script src="{{asset('assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js')}}""></script>
	<script src=" {{asset('assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js')}}"></script>

<!-- jQuery Scrollbar -->
<script src="{{asset('assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js')}}"></script>


<!-- Chart JS -->
<script src="{{asset('assets/js/plugin/chart.js/chart.min.js')}}"></script>

<!-- jQuery Sparkline -->
<script src="{{asset('assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Chart Circle -->
<script src="{{asset('assets/js/plugin/chart-circle/circles.min.js')}}"></script>

<!-- Datatables -->
<script src="{{asset('assets/js/plugin/datatables/datatables.min.js')}}"></script>

<!-- Bootstrap Notify -->
<script src="{{asset('assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js')}}"></script>

<!-- jQuery Vector Maps -->
<script src="{{asset('assets/js/plugin/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('assets/js/plugin/jqvmap/maps/jquery.vmap.world.js')}}"></script>

<!-- Sweet Alert -->
<script src="{{asset('assets/js/plugin/sweetalert/sweetalert.min.js')}}"></script>

<!-- Atlantis JS -->
<script src="{{asset('assets/js/atlantis.min.js')}}"></script>

<!-- Atlantis DEMO methods, don't include it in your project! -->
<script src="{{asset('assets/js/setting-demo.js')}}"></script>
<script src="{{asset('assets/js/demo.js')}}"></script>
<script>
    $('#lineChart').sparkline([102,109,120,99,110,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: 'rgba(255, 255, 255, .5)',
			fillColor: 'rgba(255, 255, 255, .15)'
		});

		$('#lineChart2').sparkline([99,125,122,105,110,124,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: 'rgba(255, 255, 255, .5)',
			fillColor: 'rgba(255, 255, 255, .15)'
		});

		$('#lineChart3').sparkline([105,103,123,100,95,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: 'rgba(255, 255, 255, .5)',
			fillColor: 'rgba(255, 255, 255, .15)'
		});
</script>

resources/views/includes/footerlinks1.blade.php
<script src="{{asset('assets/js/core/popper.min.js')}}"></script>
<script src="{{asset('assetShop/js/jquery-3.3.1.min.js')}}"></script>
<script src="{{asset('assetShop/js/jquery-ui.js')}}"></script>
<script src="{{asset('assetShop/js/popper.min.js')}}"></script>
<script src="{{asset('assetShop/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assetShop/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('assetShop/js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{asset('assetShop/js/aos.js')}}"></script>

<script src="{{asset('assetShop/js/main.js')}}"></script>

resources/views/includes/footerpub.blade.php
<footer class="container-fluid text-center">
    <p>Online Store Copyright</p>
    <form class="form-inline">Get deals:
        <input type="email" class="form-control" size="50" placeholder="Email Address">
        <button type="button" class="btn btn-danger">Sign Up</button>
    </form>
</footer>

resources/views/includes/header1.blade.php
<header class="site-navbar" role="banner">
    <div class="site-navbar-top">
        <div class="container">
            <div class="row align-items-center">

                <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
                    <form action="{{url('search')}}" method="post" class="site-block-top-search">
                        {{ csrf_field() }}
                        <span class="icon icon-search2"></span>
                        <input type="text" name="search" class="form-control border-0 search" id="search"
                            placeholder="Search">
                    </form>

                </div>

                <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
                    <div class="site-logo">
                        <a href="index.html" class="js-logo-clone">Digital man</a>
                    </div>
                </div>

                <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                    <div class="site-top-icons">
                        <ul>
                            <li><a href="#"><span class="icon icon-person"></span></a></li>
                            <li><a href="#"><span class="icon icon-heart-o"></span></a></li>
                            <li>
                                <a href="{{url('cart1')}}" class="site-cart">
                                    <span class="icon icon-shopping_cart"></span>
                                    <span class="count">{{ count((array) session('cart')) }}</span>
                                </a>
                            </li>
                            <li class="d-inline-block d-md-none ml-md-0"><a href="#"
                                    class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <nav class="site-navigation text-right text-md-center" role="navigation">
        <div class="container">
            <ul class="site-menu js-clone-nav d-none d-md-block">
                <li class=" active">
                    {{-- <li class="has-children active"> --}}
                    <a href="{{url('shoppers')}}">Home</a>
                    {{-- <ul class="dropdown">
                        <li><a href="#">Menu One</a></li>
                        <li><a href="#">Menu Two</a></li>
                        <li><a href="#">Menu Three</a></li>
                        <li class="has-children">
                            <a href="#">Sub Menu</a>
                            <ul class="dropdown">
                                <li><a href="#">Menu One</a></li>
                                <li><a href="#">Menu Two</a></li>
                                <li><a href="#">Menu Three</a></li>
                            </ul>
                        </li>
                    </ul> --}}
                </li>
                {{-- <li class="has-children"> --}}
                <li class="">
                    <a href="about.html">About</a>
                    {{-- <ul class="dropdown">
                        <li><a href="#">Menu One</a></li>
                        <li><a href="#">Menu Two</a></li>
                        <li><a href="#">Menu Three</a></li>
                    </ul> --}}
                </li>
                <li><a href="{{url('shop')}}">Shop</a></li>
                {{-- <li><a href="#">Catalogue</a></li>
                <li><a href="#">New Arrivals</a></li> --}}
                <li><a href="contact.html">Contact</a></li>
            </ul>
        </div>
    </nav>
</header>

@section('scripts')
<script>
    $(document).ready(function() {
        $("#search").on("keyup", function (e) {

            e.preventDefault();
           $search=$(this).val();
            $.ajax({
            url: '{{ url('search') }}',
            method: "POST",
            data:{'search': $search,
            _token : '{{ csrf_token() }}'},
            success: function (response) {
                console.log('Response from ajax ',response)
                let output = ''


                response.forEach(item => {
                    let url = "{{ route('show', '%id%')}}" ;
                    url = url.replace('%id%', item.id)
                    let asset = "{{ asset('storage/%image%')}}"
                    asset = asset.replace('%image%', item.image)

                    let url1 = "{{ route('add', '%id%')}}"
                    url1 = url1.replace('%id%', item.id)
                    // console.log(url)
                    let container = `
                        <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                            <div class="block-4 text-center border">
                                <figure class="block-4-image">
                                    <a href="${url}">
                                    <img src="${asset}"
                                            alt="Image placeholder" class="img-fluid" style= "height:200px">
                                        </a>
                                </figure>
                                <div class="block-4-text p-4">
                                    <h3>${item.title}</h3>
                                    <p class="mb-0">Finding perfect products</p>
                                    <p class="text-primary font-weight-bold">${item.discount_price}</p></a>

                                    <a href="${url1}">
                                        <button id="" class="btn btn-primary btn-sm centa add-to-cart">Add to cart
                                        </button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    `
                    output += container;
                });
                $('#products').html(output);
                console.log(response)

            }

            });
        });
    })

</script>
@endsection

resources/views/includes/headerlinks.blade.php
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Atlantis Lite - Bootstrap 4 Admin Dashboard</title>
<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
<link rel="icon" href="{{asset('assets/img/icon.ico')}}" type="image/x-icon" />
<link rel="stylesheet" href="{{asset('assets/fonts/font-awesome/css/font-awesome.min.css')}}">

<!-- Fonts and icons -->
<script src="{{asset('assets/js/plugin/webfont/webfont.min.js')}}"></script>
<script>
    WebFont.load({
			google: {"families":["Lato:300,400,700,900"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['assets/css/fonts.min.css']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
</script>

<!-- CSS Files -->
<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/atlantis.min.css')}}">

<!-- CSS Just for demo purpose, don't include it in your project -->
<link rel="stylesheet" href="{{asset('assets/css/demo.css')}}">

resources/views/includes/headerlinks1.blade.php
<title>The Trends &mdash; Online Store</title>
<meta name="_token" content="{{ csrf_token() }}">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
<link rel="stylesheet" href="{{asset('assetShop/fonts/icomoon/style.css')}}">

<link rel="stylesheet" href="{{asset('assetShop/css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('assetShop/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('assetShop/css/jquery-ui.css')}}">
<link rel="stylesheet" href="{{asset('assetShop/css/owl.carousel.min.css')}}">
<link rel="stylesheet" href="{{asset('assetShop/css/owl.theme.default.min.css')}}">
<script src="{{asset('bstrap/js/jquery-2.2.0.min.js')}}"></script>
{{-- <link rel="stylesheet" href="{{asset('bstrap/js/jquery-2.2.0.min.js')}}"> --}}


<link rel="stylesheet" href="{{asset('assetShop/css/aos.css')}}">

<link rel="stylesheet" href="{{asset('assetShop/css/style.css')}}">

resources/views/includes/logoheader.blade.php
<div class="logo-header" data-background-color="blue">

    <a href="index.html" class="logo">
        <img src="{{asset('assets/img/logo.svg')}}" alt="navbar brand" class="navbar-brand">
    </a>
    <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
            <i class="icon-menu"></i>
        </span>
    </button>
    <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
    <div class="nav-toggle">
        <button class="btn btn-toggle toggle-sidebar">
            <i class="icon-menu"></i>
        </button>
    </div>
</div>

resources/views/includes/sidebar.blade.php
<div class="sidebar sidebar-style-2" data-background-color="dark2">
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <div class="user">
                <div class="avatar-sm float-left mr-2">
                    <img src="{{asset('assets/img/profile.jpg')}}" alt="..." class="avatar-img rounded-circle">
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                        <span>
                            Oracle
                            <span class="user-level">Administrator</span>
                            <span class="caret"></span>
                        </span>
                    </a>
                    <div class="clearfix"></div>

                    <div class="collapse in" id="collapseExample">
                        <ul class="nav">
                            <li>
                                <a href="#profile">
                                    <span class="link-collapse">My Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#edit">
                                    <span class="link-collapse">Edit Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#settings">
                                    <span class="link-collapse">Settings</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <ul class="nav nav-primary">
                <li class="nav-item active">
                    <a data-toggle="collapse" href="#dashboard" class="collapsed" aria-expanded="false">
                        <i class="fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                    <div class="collapse" id="dashboard">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{{route('admin.index')}}">
                                    <span class="sub-item">Dashboard 1</span>
                                </a>
                            </li>

                        </ul>
                    </div>
                </li>
                <li class="nav-section">
                    <span class="sidebar-mini-icon">
                        <i class="fa fa-ellipsis-h"></i>
                    </span>
                    <h4 class="text-section">Components</h4>
                </li>
                <li class="nav-item">
                    <a data-toggle="collapse" href="#base">
                        <i class="fas fa-layer-group"></i>
                        <p>Base</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse" id="base">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="">
                                    <span class="sub-item">Avatars</span>
                                </a>
                            </li>


                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="{{route('categories.create')}}">
                        <i class="fas fa-th-list"></i>
                        <p>Add Categories</p>
                    </a>

                </li>
                <li class="nav-item">
                    <a href="{{route('products.create')}}">
                        <i class="fas fa-pen-square"></i>
                        <p>Add Products</p>
                    </a>

                </li>

                <li class="nav-item">
                    <a data-toggle="collapse" href="{{route('admin.index')}}">
                        <i class="fas fa-pen-square"></i>
                        <p>Add more..</p>
                    </a>

                </li>

                {{-- <li class="mx-4 mt-2">
                    <a href="http://themekita.com/atlantis-bootstrap-dashboard.html"
                        class="btn btn-primary btn-block"><span class="btn-label mr-2"> <i class="fa fa-heart"></i>
                        </span>Buy Pro</a>
                </li> --}}
            </ul>
        </div>
    </div>
</div>