routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// use App\Http\Controllers\PublicController;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\SearchController;

Route::get('/', function () {
    return view('welcome');
});
// Route::get('admin', 'AdminHomeController@index')->name('admin.dashboard');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('index', 'PublicController');
Route::resource('admin', 'AdminHomeController');
Route::put('products/{id}/feature', 'ProductsController@feature')->name('prod.update');
Route::get('product/{id}', 'HomeController@product')->name('product');
Route::post('search', 'HomeController@search')->name('search');
Route::post('home', 'HomeController@searchHome')->name('home');
Route::get('checkout', 'ProductsController@checkout')->name('checkout');
Route::get('register', 'ProductsController@register')->name('register');


Route::get('/shoppers', 'HomeController@index');
Route::get('/ind', 'PublicController@index');
Route::get('/shop', 'HomeController@shop');
Route::get('/show/{id}', 'HomeController@show')->name('show');
Route::get('/cart1', 'HomeController@cart1');
Route::get('add-to-cart/{id}', 'HomeController@addToCart')->name('add');
Route::patch('update-cart', 'HomeController@update');
Route::delete('remove', 'HomeController@remove');


Route::get('/search', 'SearchController@search');
Route::get('/index', 'SearchController@index');


// Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'status', 'image'];
    //

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.categories.create', compact('categories'));
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->file('image'));
        $data = $request->validate([
            'name' => 'string|required',
            'status' => 'boolean|required',
            'image' => 'image|required'
        ]);

        $imageName = $request->file('image')->store('category');

        // dd($imageName);

        $category = new Category(
            [
                'name' => $data['name'],
                'status' => $data['status'],
                'image' => $imageName
            ]
        );

        $category->save();

        return redirect()->back()->with('message', 'Category added successfully.');
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Category::findOrFail($id)->update($request->all());

        return redirect()->back();
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    // public function changeStatus(Request $request)
    // {
    //     $user = Category::find($request->id);
    //     $user->status = $request->status;
    //     $user->save();

    //     return response()->json(['success' => 'Status changed successfully.']);
    // }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="main-panel">
    <div class="content">
        <div class="page-inner">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Add Category</div>
                        </div>
                        @if($errors->any())
                        @foreach ($errors->all() as $error)
                        {{ $error }}
                        @endforeach
                        @endif
                        <div class="card-body">
                            <form action="{{route('categories.store')}}" method="POST" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                <div class="row">
                                    <div class="col-md-6 col-lg-4">
                                        <div class="form-group">
                                            <label for="email2">Categories</label>
                                            <input type="text" class="form-control" name="name" id="email2"
                                                placeholder="Enter category">

                                        </div>

                                        <div class="form-group">
                                            <label for="exampleFormControlSelect1">Status</label>
                                            <select required class="form-control" name="status"
                                                id="exampleFormControlSelect1">
                                                <option value=" 0" selected>0</option>
                                                <option value=" 1 "> 1 </option>
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label for="email2">Image</label>
                                            <input type="file" class="form-control" name="image" id="email2"
                                                placeholder="choose image" required>

                                        </div>

                                    </div>
                                </div>
                                <div class="card-action">
                                    <button class="btn btn-success">Submit</button>
                                </div>
                            </form>
                        </div>
                        <hr style="background-color:red">
                        <div class="row">
                            <div class="col-md-6 col-lg-4">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title">Category Table</div>
                                    </div>
                                    <div class="card-body">

                                        <table class="table mt-3">
                                            <thead>
                                                <tr>
                                                    <th scope="col">S/N</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">status</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($categories as $i => $category)
                                                <tr>
                                                    <td>{{$i + 1}}</td>
                                                    <td>{{$category->name}}</td>
                                                    <td>
                                                        @if($category->status == 1)
                                                        <form action="{{route('categories.update', $category->id)}}"
                                                            method="post">
                                                            {{csrf_field()}}
                                                            {{method_field('PUT')}}
                                                            <input type="hidden" name="status" value="0">
                                                            <div class="form-group">
                                                                <button type="submit"
                                                                    class="btn btn-sm btn-info">Enable</button>
                                                            </div>
                                                        </form>
                                                        @else
                                                        <form action="{{route('categories.update', $category->id)}}"
                                                            method="post">
                                                            {{csrf_field()}}
                                                            {{method_field('PUT')}}
                                                            <input type="hidden" name="status" value="1">
                                                            <div class="form-group">
                                                                <button type="submit"
                                                                    class="btn btn-sm btn-success">Dissable</button>
                                                            </div>
                                                        </form>
                                                        @endif
                                                    </td>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="center" style="margin-left:40%">
                                    {{-- {{$products->links()}} --}}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    @endsection
    {{-- @section('scripts')
    <script>
        $(function() {
        $('.toggle-class').change(function() {
            var status = $(this).prop('checked') == true ? 1 : 0;
            var user_id = $(this).data('id');

            $.ajax({
                type: "GET",
                dataType: "json",
                url: '/changeStatus',
                data: {'status': status, 'id': id},
                success: function(data){
                  console.log(data.success)
                }
            });
        })
      })
    </script>
    @endsection --}}

    {{-- {{ $order->quantity == 1 ? 'selected' : '' }} --}}

    {{-- {{-- <input data-id="{{$category->id}}" class="toggle-class"
    type="checkbox" data-onstyle="success"
    data-offstyle="danger" data-toggle="toggle" data-on="Active"
    data-off="InActive"
    {{ $category->status ? 'checked' : '' }}
    </td>

    </tr>
    @endforeach --}}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="main-panel">
    <div class="content">
        <div class="page-inner">

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">Add Category</div>
                        </div>
                        <div class="card-body">
                            <form action="categories.store" method="POST">
                                {{ csrf_field() }}
                                <div class="row">
                                    <div class="col-md-6 col-lg-4">
                                        <div class="form-group">
                                            <label for="email2">Categories</label>
                                            <input type="email" class="form-control" name="name" id="email2"
                                                placeholder="Enter category">
                                            <small id="emailHelp2" class="form-text text-muted">We'll never share your
                                                email
                                                with anyone else.</small>
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleFormControlSelect1">Status</label>
                                            <select class="form-control" id="exampleFormControlSelect1">
                                                <option>1</option>
                                                <option>2</option>

                                            </select>
                                        </div>


                                    </div>
                                </div>
                                <div class="card-action">
                                    <button class="btn btn-success">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                @endsection